# SparkSQL and DataFrames 

<a href = "http://yogen.io"><img src="http://yogen.io/assets/logo.svg" alt="yogen" style="width: 200px; float: right;"/></a>

In [2]:
from google.colab import drive
from os.path import join

ROOT = '/content/drive'     # default for the drive
PROJ = 'Drive access Data Science'       # path to your project on Drive

drive.mount(ROOT)           # we mount the drive at /content/drive

PROJECT_PATH = join(ROOT, PROJ)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
from google.colab import drive
drive.mount('/content/drive/My\Drive/REPOS-Github/master-data-science', force_remount=True)

ValueError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## RDDs, DataSets, and DataFrames

RDDs are the original interface for Spark programming.

DataFrames were introduced in 1.3

Datasets were introduced in 1.6, and unified with DataFrames in 2.0

### Advantages of DataFrames:

from https://www.datacamp.com/community/tutorials/apache-spark-python:

> More specifically, the performance improvements are due to two things, which you’ll often come across when you’re reading up DataFrames: custom memory management (project Tungsten), which will make sure that your Spark jobs much faster given CPU constraints, and optimized execution plans (Catalyst optimizer), of which the logical plan of the DataFrame is a part.

## SparkSQL and DataFrames 


pyspark does not have the Dataset API, which is available only if you use Spark from a statically typed language: Scala or Java.

From https://spark.apache.org/docs/2.4.4/sql-programming-guide.html

> A DataFrame is a Dataset organized into named columns. It is conceptually equivalent to a table in a relational database or a data frame in R/Python, but with richer optimizations under the hood. DataFrames can be constructed from a wide array of sources such as: structured data files, tables in Hive, external databases, or existing RDDs. The DataFrame API is available in Scala, Java, Python, and R. In Scala and Java, a DataFrame is represented by a Dataset of Rows. In the Scala API, DataFrame is simply a type alias of Dataset[Row]. While, in Java API, users need to use Dataset&lt;Row> to represent a DataFrame.

### The pyspark.sql module

Important classes of Spark SQL and DataFrames:

* `pyspark.sql.SparkSession` Main entry point for DataFrame and SQL functionality.

* `pyspark.sql.DataFrame` A distributed collection of data grouped into named columns.

* `pyspark.sql.Column` A column expression in a DataFrame.

* `pyspark.sql.Row` A row of data in a DataFrame.

* `pyspark.sql.GroupedData` Aggregation methods, returned by DataFrame.groupBy().

* `pyspark.sql.DataFrameNaFunctions` Methods for handling missing data (null values).

* `pyspark.sql.DataFrameStatFunctions` Methods for statistics functionality.

* `pyspark.sql.functions` List of built-in functions available for DataFrame.

* `pyspark.sql.types` List of data types available.

* `pyspark.sql.Window` For working with window functions.

http://spark.apache.org/docs/2.4.4/api/python/pyspark.sql.html

https://spark.apache.org/docs/2.4.4/sql-programming-guide.html

## SparkSession

The traditional way to interact with Spark is the SparkContext. In the notebooks we get that from the pyspark driver.

From 2.0 we can use SparkSession to replace SparkConf, SparkContext and SQLContext

### If you are running this notebook in Google Colab

Copy the following to a code cell and run it. It will install and set up Spark for you.

```python
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://apache.uvigo.es/spark/spark-2.4.6/spark-2.4.6-bin-hadoop2.7.tgz
!tar -xf spark-2.4.6-bin-hadoop2.7.tgz
!pip install -q findspark pyspark==2.4.6

import os
import findspark
from pyspark.sql import SparkSession

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.6-bin-hadoop2.7"
findspark.init()
spark = SparkSession.builder.master("local[*]").getOrCreate()
```

In [15]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://apache.uvigo.es/spark/spark-2.4.6/spark-2.4.6-bin-hadoop2.7.tgz
!tar -xf spark-2.4.6-bin-hadoop2.7.tgz
!pip install -q findspark pyspark==2.4.6
 
import os
import findspark
from pyspark.sql import SparkSession
 
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.6-bin-hadoop2.7"
findspark.init()
spark = SparkSession.builder.master("local[*]").getOrCreate()

     |████████████████████████████████| 218.4MB 36kB/s
     |████████████████████████████████| 204kB 42.4MB/s
  Building wheel for pyspark (setup.py) ... done

#### Passing other options to spark session:

In [63]:
spark = SparkSession.builder.config('someconfigkey', 'comconfigvalue').getOrCreate()

We can check option values in the resulting session like this:

In [ ]:
spark.

### Creating DataFrames

SparkSession.createDataFrame: from an RDD, a list or a pandas.DataFrame.

In [69]:
import random

import pyspark
from pyspark.sql import types
from pyspark.sql import functions
from pyspark.sql import SQLContext
from pyspark import SparkContext


random.seed(42)
n = 20
creatures = random.choices(['elf', 'orc', 'halfling'], k = n)

rows = list(zip(range(n), creatures))
rows

[(0, 'orc'),
 (1, 'elf'),
 (2, 'elf'),
 (3, 'elf'),
 (4, 'halfling'),
 (5, 'halfling'),
 (6, 'halfling'),
 (7, 'elf'),
 (8, 'orc'),
 (9, 'elf'),
 (10, 'elf'),
 (11, 'orc'),
 (12, 'elf'),
 (13, 'elf'),
 (14, 'orc'),
 (15, 'orc'),
 (16, 'elf'),
 (17, 'orc'),
 (18, 'halfling'),
 (19, 'elf')]

### Creating DataFrames

* From RDDs
* from Hive tables
* From Spark sources: parquet (default), json, jdbc, orc, libsvm, csv, text

In [ ]:
df = spark.createDataFrame(rows)
df.show(5)

+---+--------+
| _1|      _2|
+---+--------+
|  0|     orc|
|  1|     elf|
|  2|     elf|
|  3|     elf|
|  4|halfling|
+---+--------+
only showing top 5 rows

In [ ]:
df = spark.createDataFrame(rows, schema=['id', 'race'])
df.show(5)

+---+--------+
| id|    race|
+---+--------+
|  0|     orc|
|  1|     elf|
|  2|     elf|
|  3|     elf|
|  4|halfling|
+---+--------+
only showing top 5 rows

#### From RDDs

+---+--------+
| _1|      _2|
+---+--------+
|  0|     orc|
|  1|     elf|
|  2|     elf|
|  3|     elf|
|  4|halfling|
+---+--------+
only showing top 5 rows

+---+--------+
| id|    race|
+---+--------+
|  0|     orc|
|  1|     elf|
|  2|     elf|
|  3|     elf|
|  4|halfling|
+---+--------+
only showing top 5 rows

### Inferring and specifying schemas

#### Fully specifying a schema

We need to create a `StructType` composed of `StructField`s. each of those specifies afiled with name, type and `nullable` properties.

#### From csv files

We can either read them directly into dataframes or read them as RDDs and transform that into a DataFrame. This second way will be very useful if we have unstructured data like web server logs.

#### From other types of data

Apache Parquet is a free and open-source column-oriented data store of the Apache Hadoop ecosystem. It is similar to the other columnar storage file formats available in Hadoop namely RCFile and Optimized RCFile. It is compatible with most of the data processing frameworks in the Hadoop environment.

### Basic operations with DataFrames

### Filtering and selecting

Syntax inspired in SQL.

In [ ]:
df.select

If we want to filter, we will need to build an instance of `Column`, using square bracket notation.

That's because a comparison between str and int will error out, so spark will not even get the chance to infer to which column we are referring.

`where` is exactly synonimous with `filter`

A column is quite different to a Pandas Series. It is just a reference to a column, and can only be used to construct sparkSQL expressions (select, where...). It can't be collected or taken as a one-dimensional sequence:

#### Exercise

Extract all employee ids which correspond to orcs

In [ ]:
df.filter(df['race'] == "orc").show()

+---+----+
| id|race|
+---+----+
|  0| orc|
|  8| orc|
| 11| orc|
| 14| orc|
| 15| orc|
| 17| orc|
+---+----+

In [ ]:
df.filter(df['race'] == 'orc').select('id').show()

+---+
| id|
+---+
|  0|
|  8|
| 11|
| 14|
| 15|
| 17|
+---+

### Adding columns

Dataframes are immutable, since they are built on top of RDDs, so we can not assign to them. We need to create new DataFrames with the appropriate columns.

In [ ]:
df.withColumn

### User defined functions

There are many useful functions in pyspark.sql.functions. These work on columns, that is, they are vectorial.

We can write User Defined Functions (`udf`s), which allow us to "vectorize" operations: write a standard function to process single elements, then build a udf with that that works on columns in a DataFrame, like a SQL function.

In [ ]:
df

This errors out because 

```python
math.log1p
```

is not a udf: it doesn't know how to work with strings or Column objects:

But we can transform it into a udf:

We can do the same with any function we dream up:

If we want the resulting columns to be of a particular type, we need to specify the return type. This is because in Python return types can not be inferred.

Think about this function: what is its return type?

#### Exercise: 

Create a 'hitpoints' field in our df. make it 30000 for halflings, 40000 for elves and 70000 for orcs.

In [29]:
from pyspark.sql import functions

def hp(race):
  hps = {'elf':40000, 'halflings':30000, 'orc': 70000}
  return hps['race']

hp_udf = functions.udf(hp, returnType=types.IntegerType())

df3 = df.withColumn('hp', hp_udf('race'))
df3.show(4)

NameError: ignored

In [27]:


def hitpoints_function(column): 
  if column == 'orc': 
    return 70000 
  elif column == 'halflings': 
    return 30000
  else:
    return 40000 


my_udf = functions.udf(hitpoints_function, returnType=types.IntegerType()) 


df3 = df.withColumn('hitpoints', my_udf('race')) 
df3.show(5)

SyntaxError: ignored

If we have a column that is not the desired type, we can convert it with `cast`.

### Summary statistics

https://databricks.com/blog/2015/06/02/statistical-and-mathematical-functions-with-dataframes-in-spark.html

### .crosstab()

Crosstab returns the contingency table for two columns, as a DataFrame.

### Grouping

Grouping works very similarly to Pandas: executing groupby (or groupBy) on a DataFrame will return an object (a GroupedData) that can then be aggregated to obtain the results.

GroupedData has several aggregation functions defined:

We can do several aggregations in a single step, with a number of different syntaxes:

### Intersections

Ver much like SQL joins. We can specify the columns and the join method (left, right, inner, outer) or we can let Spark infer them.

In [38]:
data = zip(random.choices(['Mordor', 'Gondor', 'Numenor'], k=40), random.choices(range(20000,50000), k = 40))

other = spark.createDataFrame(data, schema = ['land', 'gold'])
other.show()

+-------+-----+
|   land| gold|
+-------+-----+
| Mordor|30179|
| Gondor|45850|
|Numenor|27459|
| Mordor|25706|
| Mordor|33458|
|Numenor|32656|
| Gondor|28356|
| Gondor|27494|
| Gondor|47697|
| Mordor|33293|
| Mordor|45840|
| Gondor|36509|
| Gondor|21517|
| Mordor|49978|
| Mordor|45080|
| Mordor|49069|
| Gondor|47791|
| Mordor|45460|
|Numenor|24989|
|Numenor|34569|
+-------+-----+
only showing top 20 rows

Spark refuses to do cross joins by default. To perform them, we can 

a) Allow then explicitly:

```python
spark.conf.set("spark.sql.crossJoin.enabled", "true")
```

b) Specify the join criterion

```python
df4.join(new_df, on='id').show()
```

#### Digression

We can monitor our running jobs and storage used at the Spark Web UI. We can get its url with sc.uiWebUrl.

StorageLevels represent how our DataFrame is cached: we can save the results of the computation up to that point, so that if we process several times the same data only the subsequent steps will be recomputed.

We can erase it with `unpersist`

#### Exercise

Calculate the [z-score](http://www.statisticshowto.com/probability-and-statistics/z-score/) of each employee's hitpoints for their location

In [56]:
import pyspark
from pyspark.sql import types
from pyspark.sql import functions
from pyspark.sql import SQLContext
from pyspark import SparkContext

import random

sc = SparkContext(appName="PythonStreamingQueueStream")
sqlContext = SQLContext(sc)

schemaPeople = sqlContext.createDataFrame(people)

random.seed(42)
n = 20
creatures = random.choices(['elf', 'orc', 'halfling'], k = n)

rows = list(zip(range(n), creatures))

df = spark.createDataFrame(rows, schema=['id', 'race'])

hp_udf = functions.udf(hp, returnType=types.IntegerType())

df3 = df.withColumn('hp', hp_udf('race'))
df3.show(5)

land = functions.udf(lambda : random.choice(['Gondor', 'Shire', 'Mordor']))

df4 = df3.withColumn('land', land())
df4.show(5)

ValueError: ignored

1) Calculate the mean and std of hitpoints for each location

In [57]:
def zscore(xi, mean, std):
 return (xi - mean) / std

z_udf = functions.udf(zscore, returnType=types.DoubleType())

annotated.withColumn('z', z_udf('hp', 'avg_hp', 'std_hp')).show()

NameError: ignored

2) Annotate each employee with the stats corresponding to their location

3) Calculate the z-score

Note that we can build more complex boolean conditions for joining, as well as joining on columns that do not have the same name:

### Handling null values

## SQL querying

We need to register our DataFrame as a table in the SQL context in order to be able to query against it.

Once registered, we can perform queries as complex as we want.

## Interoperation with Pandas

Easy peasy. We can convert a spark DataFrame into a Pandas one, which will `collect` it, and viceversa, which will distribute it.

## Writing out

#### Exercise

Repeat the exercise from the previous notebook, but this time with DataFrames.

Get stats for all tickets with destination MAD from `coupons150720.csv`.

You will need to extract ticket amounts with destination MAD, and then calculate:

1. Total ticket amounts per origin
2. Top 10 airlines by average amount

In [91]:
spark = SparkSession.builder.config('someconfigkey', 'comconfigvalue').getOrCreate()

import pyspark
from pyspark.sql import types
from pyspark.sql import functions
from pyspark.sql import SQLContext
from pyspark import SparkContext

coupons = spark.sql('''SELECT CAST(_c0 AS BIGINT) AS tkt_number,
                              CAST(_c1 AS INT) AS cpn_number,
                              _c2 AS origin,
                              _c3 AS dest,
                              _c4 AS carrier,
                              CAST(_c6 AS FLOAT) AS amount
                        FROM csv.`coupon150720.csv.gz`''')

coupons.show()

+--------------+----------+------+----+-------+------+
|    tkt_number|cpn_number|origin|dest|carrier|amount|
+--------------+----------+------+----+-------+------+
|79062005698500|         1|   MAA| AUH|     9W| 56.79|
|79062005698500|         2|   AUH| CDG|     9W| 84.34|
|79062005924069|         1|   CJB| MAA|     9W|  60.0|
|79065668570385|         1|   DEL| DXB|     9W|160.63|
|79065668737021|         1|   AUH| IXE|     9W|152.46|
|79062006192650|         1|   RPR| BOM|     9W|  68.5|
|79062006192650|         2|   BOM| RPR|     9W|  68.5|
|79062005733853|         1|   DEL| DED|     9W| 56.16|
|79062005836987|         1|   ATL| LGA|     AA|  28.3|
|79062005836987|         2|   LGA| EWR|   null|   0.0|
|79062005836987|         3|   EWR| BOM|     9W|176.09|
|79062005836987|         4|   BOM| AMD|     9W| 12.02|
|79062005836987|         5|   AMD| BOM|     9W| 12.02|
|79062005836987|         6|   BOM| EWR|     9W|176.09|
|79062005836987|         7|   EWR| ATL|     UA|  28.3|
|79062005862818|         1|   LHR| BOM|     9W|101.65|
|79062005862818|         2|   BOM| HKG|     9W| 57.76|
|79065668498895|         1|   DXB| BOM|     9W| 54.44|
|79065668498895|         2|   BOM| DXB|     9W|  73.5|
|79062005534346|         1|   KTM| DEL|     9W| 24.92|
+--------------+----------+------+----+-------+------+
only showing top 20 rows

1) Extract the fields you need (c0,c1,c2,c3,c4 and c6) into a dataframe with proper names and types

Remember, you want to calculate:

Total ticket amounts per origin

Top 10 airlines by average amount

+------+------------------+
|origin|       sum(amount)|
+------+------------------+
|   PMI| 40547.17005729675|
|   YUL|284.44000244140625|
|   HEL| 8195.760055541992|
|   SXB| 264.4599914550781|
|   UIO| 8547.599964141846|
+------+------------------+
only showing top 5 rows

2) Total ticket amounts per origin

In [ ]:
coupons.where(coupons['dest'] == 'MAD')\
.groupby('origin')\
.sum('amount').show(5)

3) Top 10 Airlines by average amount

In [94]:
coupons.where(coupons['dest'] == 'MAD')\
.groupBy('carrier')\
.avg('amount')\
.sort('avg(amount)', ascending = False)\
.show(10)

+-------+------------------+
|carrier|       avg(amount)|
+-------+------------------+
|     V0| 5418.098665364583|
|     AC|  740.619985961914|
|     KE| 688.5261500431941|
|     SV|  553.174259916265|
|     OB| 535.5044420030382|
|     AR| 513.5304808843704|
|     AV| 450.1950941518613|
|     AM| 440.7342111687911|
|     C2| 397.8699951171875|
|     LA|379.95370341954606|
+-------+------------------+
only showing top 10 rows

## Further Reading

https://databricks.com/blog/2016/07/14/a-tale-of-three-apache-spark-apis-rdds-dataframes-and-datasets.html

https://www.datacamp.com/community/tutorials/apache-spark-python

https://spark.apache.org/docs/2.2.0/sql-programming-guide.html

https://ogirardot.wordpress.com/2015/05/29/rdds-are-the-new-bytecode-of-apache-spark/

https://stackoverflow.com/questions/36822224/what-are-the-pros-and-cons-of-parquet-format-compared-to-other-formats

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/PySpark_SQL_Cheat_Sheet_Python.pdf